### ISSUE TITLE
SplitMix32's mkSeedTime only has second-granularity precision

### ISSUE THREAD

**Issue by jrtc27** [haskellari/splitmix#45]
The current implementation is:
https://github.com/phadej/splitmix/blob/aea2ddff0afeacb6ef5aef418ef1fd07203024d2/src/System/Random/SplitMix32.hs#L374-L384

Thus `hi` is completely thrown away, resulting in second-granularity precision. Instead they should be mixed together somehow (or fewer bits taken from each).

**Comment by phadej** [comment]
Good catch. Yes, we don't need to `shiftL` hi, we can simply `xor hi lo`.

**Comment by jrtc27** [comment]
TBH you could also have `hi = 0` for the 64-bit GHCJS version; it shouldn't result in any additional entropy unless the algorithm itself is flawed?

**Comment by phadej** [comment]
@jrtc27 yes, `hi = 0` can be for 64bit as well.

**Comment by phadej** [comment]
I improved the initial seed generation in https://hackage.haskell.org/package/splitmix-0.1.0.2
