### ISSUE TITLE
Bump base-compat*, bytestring

### ISSUE THREAD

**Issue by andreasabel** [haskellari/splitmix#59]
See PR #58, these ub worked for me with GHC-9.2:
```
base-compat < 0.13
base-compat-batteries < 0.13
bytestring < 0.12
```

**Comment by andreasabel** [comment]
Now that a GHC-9.2 compatible [`async`](https://hackage.haskell.org/package/async) is on hackage (2.2.4), `cabal test` works with the above relaxed bounds.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/splitmix-0.1.0.4 is on hackage.
